import { DynamoDB } from "aws-sdk";
import { BrewingTypes as BT } from "brewing-shared";
import { DynamoTables } from "../../types/dynamo-tables";
import { v4 as uuid } from "uuid";

const tableName: DynamoTables = "recipes";

export const recipeTableConfig: DynamoDB.CreateTableInput = {
  TableName: tableName,
  KeySchema: [{ AttributeName: "id", KeyType: "HASH" }],
  AttributeDefinitions: [
    { AttributeName: "id", AttributeType: "S" },
    { AttributeName: "user", AttributeType: "S" },
  ],
  BillingMode: "PAY_PER_REQUEST",
  GlobalSecondaryIndexes: [
    {
      IndexName: "userIndex",
      KeySchema: [{ AttributeName: "user", KeyType: "HASH" }],
      Projection: {
        ProjectionType: "ALL",
      },
    },
  ],
};

export const recipeSeedData: BT.Recipe[] = [
  {
    author: "Bill W.",
    batchSize: 4.5,
    efficiency: 60,
    id: uuid(),
    ingredients: [
      {
        type: "Misc",
        id: uuid(),
        name: "Orange zest",
        amount: "2 oranges",
        notes: "Microplane or chop finely, add to wort at flameout",
        step: "Boil",
        timing: 0,
      },
      {
        type: "Misc",
        id: uuid(),
        name: "Coriander, ground",
        amount: "5 tsp",
        notes: "Add to wort at flamout",
        step: "Boil",
        timing: 0,
      },
      {
        type: "Misc",
        id: uuid(),
        name: "Gypsum",
        amount: "10.5 g",
        notes: "Add to strike water",
        step: "StrikeWater",
        timing: 0,
      },
      {
        type: "Culture",
        id: uuid(),
        name: "Wyeast 3787",
        attenuation: 78,
        notes: "Do a starter if you have time.",
        form: "Liquid",
        step: "Fermentor",
        timing: 0,
      },
      {
        type: "Hop",
        id: uuid(),
        name: "Magnum",
        amount: 1.5,
        timing: 60,
        alphaAcid: 12,
        step: "Boil",
        notes: "",
      },
      {
        type: "Hop",
        id: uuid(),
        name: "Citra",
        amount: 2,
        timing: 7,
        alphaAcid: 12,
        step: "Fermentor",
        notes: "",
      },
      {
        type: "Hop",
        id: uuid(),
        name: "Centennial",
        amount: 1,
        timing: 7,
        alphaAcid: 10.5,
        step: "Fermentor",
        notes: "",
      },
      {
        type: "Hop",
        id: uuid(),
        name: "Cascade",
        amount: 1,
        timing: 7,
        alphaAcid: 6,
        step: "Fermentor",
        notes: "",
      },
      {
        type: "Fermentable",
        id: uuid(),
        name: "Pilsner (Weyermann)",
        amount: 7,
        fermentableType: "Grain",
        lovibond: 1,
        gravity: 1.038,
        notes: "",
        step: "Mash",
        timing: 60,
      },
      {
        type: "Fermentable",
        id: uuid(),
        name: "Wheat",
        amount: 3,
        fermentableType: "Grain",
        lovibond: 1,
        gravity: 1.038,
        notes: "",
        step: "Mash",
        timing: 60,
      },
      {
        type: "Fermentable",
        id: uuid(),
        name: "Wheat Flaked",
        amount: 2,
        fermentableType: "Grain",
        lovibond: 2,
        gravity: 1.035,
        notes: "",
        step: "Mash",
        timing: 60,
      },
      {
        type: "Fermentable",
        id: uuid(),
        name: "Acid Malt",
        amount: 0.5,
        fermentableType: "Grain",
        lovibond: 3,
        gravity: 1.027,
        notes: "",
        step: "Mash",
        timing: 60,
      },
    ],
    measurementType: "imperial",
    name: "June's Mama IPA",
    type: "All grain",
    user: "123456789",
    description:
      "This one is a house favorite. A white IPA with orange zest and coriander added at flameout. Based on your own efficiency/volume, tweak the grain bill and bittering hops to hit an OG of low 1.060's and IBUs in the low 60's.",
  },
];
