on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Dependencies
        run: npm ci
      - name: Make script runnable
        run: chmod +x "${GITHUB_WORKSPACE}/scripts/deploy-lambda.sh"
      - name: Run deploy script
        run: "${GITHUB_WORKSPACE}/scripts/deploy-lambda.sh"
