on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Dependencies
        run: npm ci
      - name: Compile typescript
        run: tsc
      - name: Pack up zip files
        run: webpack --mode production
      - name: Sync to S3 bucket
        run: aws s3 sync "artifacts/built-lambdas/zip"  s3://${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }}
      - name: Update functions
        run: |
          aws lambda update-function-code \
            --function-name  RecipeCreateUpdate \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key RecipeCreateUpdate.zip

          aws lambda update-function-code \
            --function-name  RecipeDelete \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key RecipeDelete.zip

          aws lambda update-function-code \
            --function-name  RecipeGetById \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key RecipeGetById.zip

          aws lambda update-function-code \
            --function-name  RecipeGetByUser \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key RecipeGetByUser.zip

          aws lambda update-function-code \
            --function-name  BrewSettingsCreateUpdate \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key BrewSettingsCreateUpdate.zip

          aws lambda update-function-code \
            --function-name  BrewSettingsDelete \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key BrewSettingsDelete.zip

          aws lambda update-function-code \
            --function-name  BrewSettingsGet \
            --s3-bucket ${{ secrets.AWS_LAMBDA_S3_BUCKET_NAME_PROD }} \
            --s3-key BrewSettingsGet.zip  
